### ISSUE TITLE
Publish the extension on Open VSX

### ISSUE THREAD

**Issue by orpheuslummis** [lostintangent/wikilens#25] opened 2021-10-21 23:53 UTC
- https://open-vsx.org/
- https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

To make the extension available on Web versions of vscode. Thanks.

**Comment by lostintangent** [comment] 2021-11-20 01:19
Closing as a duplicate of #29.

**Closed by lostintangent** 2021-11-20 01:19 UTC
